# Generated by Django 5.0 on 2024-01-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_entregable_estudiante_profesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='profesio',
            new_name='profesion',
        ),
    ]
