# Generated by Django 5.0 on 2024-01-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_remove_entregable_chek_entregable_enviado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregable',
            name='enviado',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
