# Generated by Django 5.0 on 2024-01-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_alter_entregable_enviado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregable',
            name='enviado',
            field=models.BooleanField(default=True),
        ),
    ]
